name: mChats
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  clay_containers: ^0.2.2
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_custom_clippers: ^1.1.2
  flutter_signin_button: ^1.1.0
  google_fonts: ^0.3.5
  google_sign_in: ^4.5.9
  hexcolor: ^1.0.6
  page_transition: ^1.1.7+6
  random_string: ^2.1.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
